language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t oleksiisemko/docker-react -f Dockerfile.dev .  

script:
  - docker run -e CI=true oleksiisemko/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-675703781937"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "AWS_SECRET_KEY"